services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: prod
      - key: ALLOWED_ORIGINS
        value: "*"     # Or your frontend domain

    autoDeploy: true
